CREATE TABLE IF NOT EXISTS urls (
	id SERIAL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	name VARCHAR(255) NOT NULL,
	created_at DATE DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS url_checks (
	id SERIAL PRIMARY KEY,
	url_id INTEGER REFERENCES urls(id) ON DELETE CASCADE,
	status_code INTEGER,
	h1 VARCHAR(255),
	title VARCHAR(255),
	description TEXT,
	created_at DATE DEFAULT CURRENT_TIMESTAMP
);
